/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file19_types.h"
#include "file19_types.tcc"

#include <algorithm>
#include <folly/Indestructible.h>

#include "file19_data.h"

namespace example { namespace thrift19 {

void Struct0::__clear() {
  // clear all fields
  field1.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift27::Struct7>::clear(&field2);
  field3 = 0;
  field4.clear();
  field5.clear();
  __isset.__clear();
}

bool Struct0::operator==(const Struct0& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  return true;
}

const std::map<int8_t, int8_t>& Struct0::get_field1() const& {
  return field1;
}

std::map<int8_t, int8_t> Struct0::get_field1() && {
  return std::move(field1);
}

const  ::example::thrift27::Struct7& Struct0::get_field2() const& {
  return field2;
}

 ::example::thrift27::Struct7 Struct0::get_field2() && {
  return std::move(field2);
}

const std::map<std::set<int32_t>, std::string>& Struct0::get_field4() const& {
  return field4;
}

std::map<std::set<int32_t>, std::string> Struct0::get_field4() && {
  return std::move(field4);
}

const std::map<int8_t, std::string>& Struct0::get_field5() const& {
  return field5;
}

std::map<int8_t, std::string> Struct0::get_field5() && {
  return std::move(field5);
}

void Struct0::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct0& a, Struct0& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct0::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct0::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct0::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct0::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct0::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct0::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct0::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct0::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct1::__clear() {
  // clear all fields
  field1 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  ::apache::thrift::Cpp2Ops<  ::example::thrift32::Struct12>::clear(&field2);
  __isset.__clear();
}

bool Struct1::operator==(const Struct1& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  return true;
}

const  ::example::thrift32::Struct12& Struct1::get_field2() const& {
  return field2;
}

 ::example::thrift32::Struct12 Struct1::get_field2() && {
  return std::move(field2);
}

void Struct1::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct1& a, Struct1& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct1::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct1::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct1::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct1::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct1::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct1::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct1::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct1::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct2::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift27::Struct2>::clear(&field1);
  field2 = 0;
  field3 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field4 = 0;
  field5 = 0;
  field6 = 0;
  field7 = 0;
  field8.clear();
  field9 = 0;
  field10.clear();
  field11 = 0;
  field12.clear();
  field13 = 0;
  field14 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field15.clear();
  field16.clear();
  field17.clear();
  field18 = 0;
  field19 = 0;
  field20 = 0;
  field21.clear();
  field22.clear();
  field23 = 0;
  field24 = 0;
  __isset.__clear();
}

bool Struct2::operator==(const Struct2& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field3, rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  if (!((field20 == rhs.field20))) {
    return false;
  }
  if (!((field21 == rhs.field21))) {
    return false;
  }
  if (!((field22 == rhs.field22))) {
    return false;
  }
  if (!((field23 == rhs.field23))) {
    return false;
  }
  if (!((field24 == rhs.field24))) {
    return false;
  }
  return true;
}

const  ::example::thrift27::Struct2& Struct2::get_field1() const& {
  return field1;
}

 ::example::thrift27::Struct2 Struct2::get_field1() && {
  return std::move(field1);
}

const std::map<int64_t, std::vector<std::set<bool>>>& Struct2::get_field8() const& {
  return field8;
}

std::map<int64_t, std::vector<std::set<bool>>> Struct2::get_field8() && {
  return std::move(field8);
}

const std::map<float, bool>& Struct2::get_field10() const& {
  return field10;
}

std::map<float, bool> Struct2::get_field10() && {
  return std::move(field10);
}

const std::map<int32_t, int16_t>& Struct2::get_field12() const& {
  return field12;
}

std::map<int32_t, int16_t> Struct2::get_field12() && {
  return std::move(field12);
}

const std::set<int16_t>& Struct2::get_field15() const& {
  return field15;
}

std::set<int16_t> Struct2::get_field15() && {
  return std::move(field15);
}

const std::vector<double>& Struct2::get_field16() const& {
  return field16;
}

std::vector<double> Struct2::get_field16() && {
  return std::move(field16);
}

const std::map<std::string, std::set<std::vector<int64_t>>>& Struct2::get_field17() const& {
  return field17;
}

std::map<std::string, std::set<std::vector<int64_t>>> Struct2::get_field17() && {
  return std::move(field17);
}

const std::set< ::example::thrift27::Struct5>& Struct2::get_field21() const& {
  return field21;
}

std::set< ::example::thrift27::Struct5> Struct2::get_field21() && {
  return std::move(field21);
}

const std::set<double>& Struct2::get_field22() const& {
  return field22;
}

std::set<double> Struct2::get_field22() && {
  return std::move(field22);
}

void Struct2::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field20") {
    fid = 20;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field21") {
    fid = 21;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field22") {
    fid = 22;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field23") {
    fid = 23;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field24") {
    fid = 24;
    _ftype = apache::thrift::protocol::T_I16;
  }
}

void swap(Struct2& a, Struct2& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.field20, b.field20);
  swap(a.field21, b.field21);
  swap(a.field22, b.field22);
  swap(a.field23, b.field23);
  swap(a.field24, b.field24);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct2::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct2::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct2::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct2::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct2::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct2::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct2::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct2::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct3::__clear() {
  // clear all fields
  field1 = 0;
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3 = 0;
  __isset.__clear();
}

bool Struct3::operator==(const Struct3& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  return true;
}

void Struct3::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
}

void swap(Struct3& a, Struct3& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct3::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct3::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct3::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct3::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct3::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct3::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct3::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct3::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct4::__clear() {
  // clear all fields
  field1 = 0;
  field2 = 0;
  field3.clear();
  field4.clear();
  field5.clear();
  field6.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift27::Struct3>::clear(&field7);
  field8.clear();
  field9 = 0;
  field10 = 0;
  field11.clear();
  field12 = 0;
  field13 = 0;
  field14 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  ::apache::thrift::Cpp2Ops<  ::example::thrift19::Struct1>::clear(&field15);
  field16.clear();
  field17 = 0;
  field18 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field19.clear();
  field20.clear();
  field21 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  ::apache::thrift::Cpp2Ops<  ::example::thrift32::Struct19>::clear(&field22);
  field23 = 0;
  field24 = 0;
  field25.clear();
  field26 = 0;
  field27 = 0;
  field28.clear();
  field29.clear();
  field30.clear();
  field31.clear();
  __isset.__clear();
}

bool Struct4::operator==(const Struct4& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field18, rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  if (!((field20 == rhs.field20))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field21, rhs.field21))) {
    return false;
  }
  if (!((field22 == rhs.field22))) {
    return false;
  }
  if (!((field23 == rhs.field23))) {
    return false;
  }
  if (!((field24 == rhs.field24))) {
    return false;
  }
  if (!((field25 == rhs.field25))) {
    return false;
  }
  if (!((field26 == rhs.field26))) {
    return false;
  }
  if (!((field27 == rhs.field27))) {
    return false;
  }
  if (!((field28 == rhs.field28))) {
    return false;
  }
  if (!((field29 == rhs.field29))) {
    return false;
  }
  if (!((field30 == rhs.field30))) {
    return false;
  }
  if (!((field31 == rhs.field31))) {
    return false;
  }
  return true;
}

const std::map<std::string, int16_t>& Struct4::get_field3() const& {
  return field3;
}

std::map<std::string, int16_t> Struct4::get_field3() && {
  return std::move(field3);
}

const std::map<std::string, std::map<std::string, double>>& Struct4::get_field4() const& {
  return field4;
}

std::map<std::string, std::map<std::string, double>> Struct4::get_field4() && {
  return std::move(field4);
}

const std::vector<bool>& Struct4::get_field5() const& {
  return field5;
}

std::vector<bool> Struct4::get_field5() && {
  return std::move(field5);
}

const std::set<std::string>& Struct4::get_field6() const& {
  return field6;
}

std::set<std::string> Struct4::get_field6() && {
  return std::move(field6);
}

const  ::example::thrift27::Struct3& Struct4::get_field7() const& {
  return field7;
}

 ::example::thrift27::Struct3 Struct4::get_field7() && {
  return std::move(field7);
}

const std::vector<int8_t>& Struct4::get_field8() const& {
  return field8;
}

std::vector<int8_t> Struct4::get_field8() && {
  return std::move(field8);
}

const std::map<int64_t, std::string>& Struct4::get_field11() const& {
  return field11;
}

std::map<int64_t, std::string> Struct4::get_field11() && {
  return std::move(field11);
}

const  ::example::thrift19::Struct1& Struct4::get_field15() const& {
  return field15;
}

 ::example::thrift19::Struct1 Struct4::get_field15() && {
  return std::move(field15);
}

const std::set<std::string>& Struct4::get_field16() const& {
  return field16;
}

std::set<std::string> Struct4::get_field16() && {
  return std::move(field16);
}

const std::vector< ::example::thrift32::Struct10>& Struct4::get_field19() const& {
  return field19;
}

std::vector< ::example::thrift32::Struct10> Struct4::get_field19() && {
  return std::move(field19);
}

const std::set<std::map< ::example::thrift19::Struct0, bool>>& Struct4::get_field20() const& {
  return field20;
}

std::set<std::map< ::example::thrift19::Struct0, bool>> Struct4::get_field20() && {
  return std::move(field20);
}

const  ::example::thrift32::Struct19& Struct4::get_field22() const& {
  return field22;
}

 ::example::thrift32::Struct19 Struct4::get_field22() && {
  return std::move(field22);
}

const std::map<bool, double>& Struct4::get_field25() const& {
  return field25;
}

std::map<bool, double> Struct4::get_field25() && {
  return std::move(field25);
}

const std::vector<int64_t>& Struct4::get_field28() const& {
  return field28;
}

std::vector<int64_t> Struct4::get_field28() && {
  return std::move(field28);
}

const std::vector<float>& Struct4::get_field29() const& {
  return field29;
}

std::vector<float> Struct4::get_field29() && {
  return std::move(field29);
}

const std::set<float>& Struct4::get_field30() const& {
  return field30;
}

std::set<float> Struct4::get_field30() && {
  return std::move(field30);
}

const std::map<double, std::string>& Struct4::get_field31() const& {
  return field31;
}

std::map<double, std::string> Struct4::get_field31() && {
  return std::move(field31);
}

void Struct4::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field20") {
    fid = 20;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field21") {
    fid = 21;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field22") {
    fid = 22;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field23") {
    fid = 23;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field24") {
    fid = 24;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field25") {
    fid = 25;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field26") {
    fid = 26;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field27") {
    fid = 27;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field28") {
    fid = 28;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field29") {
    fid = 29;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field30") {
    fid = 30;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field31") {
    fid = 31;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct4& a, Struct4& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.field20, b.field20);
  swap(a.field21, b.field21);
  swap(a.field22, b.field22);
  swap(a.field23, b.field23);
  swap(a.field24, b.field24);
  swap(a.field25, b.field25);
  swap(a.field26, b.field26);
  swap(a.field27, b.field27);
  swap(a.field28, b.field28);
  swap(a.field29, b.field29);
  swap(a.field30, b.field30);
  swap(a.field31, b.field31);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct4::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct4::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct4::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct4::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct4::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct4::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct4::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct4::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct5::__clear() {
  // clear all fields
  field1.clear();
  __isset.__clear();
}

bool Struct5::operator==(const Struct5& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  return true;
}

const std::map<double,  ::example::thrift32::Struct9>& Struct5::get_field1() const& {
  return field1;
}

std::map<double,  ::example::thrift32::Struct9> Struct5::get_field1() && {
  return std::move(field1);
}

void Struct5::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct5& a, Struct5& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct5::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct5::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct5::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct5::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct5::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct5::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct5::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct5::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct6::__clear() {
  // clear all fields
  field1.clear();
  field2 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift19::Struct0>::clear(&field3);
  ::apache::thrift::Cpp2Ops<  ::example::thrift19::Struct3>::clear(&field4);
  __isset.__clear();
}

bool Struct6::operator==(const Struct6& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  return true;
}

const std::map<std::map<std::string, int16_t>, std::map<std::vector<double>, bool>>& Struct6::get_field1() const& {
  return field1;
}

std::map<std::map<std::string, int16_t>, std::map<std::vector<double>, bool>> Struct6::get_field1() && {
  return std::move(field1);
}

const  ::example::thrift19::Struct0& Struct6::get_field3() const& {
  return field3;
}

 ::example::thrift19::Struct0 Struct6::get_field3() && {
  return std::move(field3);
}

const  ::example::thrift19::Struct3& Struct6::get_field4() const& {
  return field4;
}

 ::example::thrift19::Struct3 Struct6::get_field4() && {
  return std::move(field4);
}

void Struct6::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct6& a, Struct6& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct6::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct6::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct6::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct6::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct6::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct6::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct6::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct6::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct7::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift32::Struct28>::clear(&field1);
  field2.clear();
  field3.clear();
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field5.clear();
  field6 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field7 = 0;
  field8 = 0;
  field9.clear();
  field10.clear();
  field11.clear();
  field12.clear();
  field13.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift19::Struct0>::clear(&field14);
  field15.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift27::Struct8>::clear(&field16);
  field17 = 0;
  field18.clear();
  field19 = 0;
  field20 = 0;
  field21 = 0;
  field22 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field23 = 0;
  __isset.__clear();
}

bool Struct7::operator==(const Struct7& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field6, rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  if (!((field20 == rhs.field20))) {
    return false;
  }
  if (!((field21 == rhs.field21))) {
    return false;
  }
  if (!((field22 == rhs.field22))) {
    return false;
  }
  if (!((field23 == rhs.field23))) {
    return false;
  }
  return true;
}

const  ::example::thrift32::Struct28& Struct7::get_field1() const& {
  return field1;
}

 ::example::thrift32::Struct28 Struct7::get_field1() && {
  return std::move(field1);
}

const std::set<double>& Struct7::get_field2() const& {
  return field2;
}

std::set<double> Struct7::get_field2() && {
  return std::move(field2);
}

const std::map<float, std::map<std::set<int32_t>, float>>& Struct7::get_field3() const& {
  return field3;
}

std::map<float, std::map<std::set<int32_t>, float>> Struct7::get_field3() && {
  return std::move(field3);
}

const std::set<int32_t>& Struct7::get_field5() const& {
  return field5;
}

std::set<int32_t> Struct7::get_field5() && {
  return std::move(field5);
}

const std::map<int32_t, double>& Struct7::get_field9() const& {
  return field9;
}

std::map<int32_t, double> Struct7::get_field9() && {
  return std::move(field9);
}

const std::set<float>& Struct7::get_field10() const& {
  return field10;
}

std::set<float> Struct7::get_field10() && {
  return std::move(field10);
}

const std::vector<float>& Struct7::get_field11() const& {
  return field11;
}

std::vector<float> Struct7::get_field11() && {
  return std::move(field11);
}

const std::map< ::example::thrift19::Struct2,  ::example::thrift19::Struct0>& Struct7::get_field12() const& {
  return field12;
}

std::map< ::example::thrift19::Struct2,  ::example::thrift19::Struct0> Struct7::get_field12() && {
  return std::move(field12);
}

const std::map<double, int16_t>& Struct7::get_field13() const& {
  return field13;
}

std::map<double, int16_t> Struct7::get_field13() && {
  return std::move(field13);
}

const  ::example::thrift19::Struct0& Struct7::get_field14() const& {
  return field14;
}

 ::example::thrift19::Struct0 Struct7::get_field14() && {
  return std::move(field14);
}

const std::map<bool, std::map<float, int8_t>>& Struct7::get_field15() const& {
  return field15;
}

std::map<bool, std::map<float, int8_t>> Struct7::get_field15() && {
  return std::move(field15);
}

const  ::example::thrift27::Struct8& Struct7::get_field16() const& {
  return field16;
}

 ::example::thrift27::Struct8 Struct7::get_field16() && {
  return std::move(field16);
}

const std::set<double>& Struct7::get_field18() const& {
  return field18;
}

std::set<double> Struct7::get_field18() && {
  return std::move(field18);
}

void Struct7::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field20") {
    fid = 20;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field21") {
    fid = 21;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field22") {
    fid = 22;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field23") {
    fid = 23;
    _ftype = apache::thrift::protocol::T_I32;
  }
}

void swap(Struct7& a, Struct7& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.field20, b.field20);
  swap(a.field21, b.field21);
  swap(a.field22, b.field22);
  swap(a.field23, b.field23);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct7::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct7::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct7::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct7::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct7::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct7::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct7::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct7::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
namespace example { namespace thrift19 {

void Struct8::__clear() {
  // clear all fields
  field1 = 0;
  field2.clear();
  field3 = 0;
  field4 = 0;
  field5.clear();
  field6.clear();
  field7 = 0;
  field8.clear();
  field9.clear();
  field10.clear();
  field11 = 0;
  field12.clear();
  field13.clear();
  field14.clear();
  __isset.__clear();
}

bool Struct8::operator==(const Struct8& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  return true;
}

const std::set<std::string>& Struct8::get_field2() const& {
  return field2;
}

std::set<std::string> Struct8::get_field2() && {
  return std::move(field2);
}

const std::set<int8_t>& Struct8::get_field5() const& {
  return field5;
}

std::set<int8_t> Struct8::get_field5() && {
  return std::move(field5);
}

const std::vector<int8_t>& Struct8::get_field6() const& {
  return field6;
}

std::vector<int8_t> Struct8::get_field6() && {
  return std::move(field6);
}

const std::map<int8_t, std::set<bool>>& Struct8::get_field8() const& {
  return field8;
}

std::map<int8_t, std::set<bool>> Struct8::get_field8() && {
  return std::move(field8);
}

const std::vector<bool>& Struct8::get_field9() const& {
  return field9;
}

std::vector<bool> Struct8::get_field9() && {
  return std::move(field9);
}

const std::set<std::vector<int16_t>>& Struct8::get_field10() const& {
  return field10;
}

std::set<std::vector<int16_t>> Struct8::get_field10() && {
  return std::move(field10);
}

const std::vector<std::string>& Struct8::get_field12() const& {
  return field12;
}

std::vector<std::string> Struct8::get_field12() && {
  return std::move(field12);
}

const std::map<int64_t, int64_t>& Struct8::get_field13() const& {
  return field13;
}

std::map<int64_t, int64_t> Struct8::get_field13() && {
  return std::move(field13);
}

const std::map<double, std::string>& Struct8::get_field14() const& {
  return field14;
}

std::map<double, std::string> Struct8::get_field14() && {
  return std::move(field14);
}

void Struct8::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct8& a, Struct8& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct8::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct8::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct8::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct8::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct8::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct8::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct8::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct8::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift19
