/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file29_types.h"
#include "file29_types.tcc"

#include <algorithm>
#include <folly/Indestructible.h>

#include "file29_data.h"

namespace example { namespace thrift29 {

void Struct0::__clear() {
  // clear all fields
  field1.clear();
  field2 = 0;
  field3 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field4.clear();
  field5.clear();
  field6.clear();
  field7.clear();
  __isset.__clear();
}

bool Struct0::operator==(const Struct0& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field3, rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  return true;
}

const std::set<bool>& Struct0::get_field1() const& {
  return field1;
}

std::set<bool> Struct0::get_field1() && {
  return std::move(field1);
}

const std::set<std::string>& Struct0::get_field4() const& {
  return field4;
}

std::set<std::string> Struct0::get_field4() && {
  return std::move(field4);
}

const std::map<std::map<float, int16_t>, int64_t>& Struct0::get_field5() const& {
  return field5;
}

std::map<std::map<float, int16_t>, int64_t> Struct0::get_field5() && {
  return std::move(field5);
}

const std::map<std::string, bool>& Struct0::get_field6() const& {
  return field6;
}

std::map<std::string, bool> Struct0::get_field6() && {
  return std::move(field6);
}

const std::set<int64_t>& Struct0::get_field7() const& {
  return field7;
}

std::set<int64_t> Struct0::get_field7() && {
  return std::move(field7);
}

void Struct0::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_SET;
  }
}

void swap(Struct0& a, Struct0& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct0::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct0::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct0::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct0::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct0::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct0::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct0::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct0::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct1::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field1);
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3 = 0;
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field5.clear();
  field6.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field7);
  field8 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field9 = 0;
  field10 = 0;
  field11.clear();
  field12 = 0;
  field13 = 0;
  field14 = 0;
  field15.clear();
  field16.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field17);
  field18 = 0;
  field19.clear();
  __isset.__clear();
}

bool Struct1::operator==(const Struct1& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  return true;
}

const  ::example::thrift29::Struct0& Struct1::get_field1() const& {
  return field1;
}

 ::example::thrift29::Struct0 Struct1::get_field1() && {
  return std::move(field1);
}

const std::vector<std::set<bool>>& Struct1::get_field5() const& {
  return field5;
}

std::vector<std::set<bool>> Struct1::get_field5() && {
  return std::move(field5);
}

const std::map< ::example::thrift29::Struct0, std::set<int32_t>>& Struct1::get_field6() const& {
  return field6;
}

std::map< ::example::thrift29::Struct0, std::set<int32_t>> Struct1::get_field6() && {
  return std::move(field6);
}

const  ::example::thrift29::Struct0& Struct1::get_field7() const& {
  return field7;
}

 ::example::thrift29::Struct0 Struct1::get_field7() && {
  return std::move(field7);
}

const std::set<std::set<std::vector<double>>>& Struct1::get_field11() const& {
  return field11;
}

std::set<std::set<std::vector<double>>> Struct1::get_field11() && {
  return std::move(field11);
}

const std::vector<int32_t>& Struct1::get_field15() const& {
  return field15;
}

std::vector<int32_t> Struct1::get_field15() && {
  return std::move(field15);
}

const std::map<int32_t, bool>& Struct1::get_field16() const& {
  return field16;
}

std::map<int32_t, bool> Struct1::get_field16() && {
  return std::move(field16);
}

const  ::example::thrift29::Struct0& Struct1::get_field17() const& {
  return field17;
}

 ::example::thrift29::Struct0 Struct1::get_field17() && {
  return std::move(field17);
}

const std::vector<std::set<std::string>>& Struct1::get_field19() const& {
  return field19;
}

std::vector<std::set<std::string>> Struct1::get_field19() && {
  return std::move(field19);
}

void Struct1::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_LIST;
  }
}

void swap(Struct1& a, Struct1& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct1::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct1::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct1::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct1::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct1::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct1::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct1::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct1::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct2::__clear() {
  // clear all fields
  field1 = 0;
  field2 = 0;
  field3.clear();
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field5 = 0;
  field6.clear();
  field7.clear();
  field8 = 0;
  field9 = 0;
  field10 = 0;
  field11.clear();
  field12.clear();
  __isset.__clear();
}

bool Struct2::operator==(const Struct2& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field4, rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  return true;
}

const std::vector< ::example::thrift29::Struct0>& Struct2::get_field3() const& {
  return field3;
}

std::vector< ::example::thrift29::Struct0> Struct2::get_field3() && {
  return std::move(field3);
}

const std::vector< ::example::thrift29::Struct0>& Struct2::get_field6() const& {
  return field6;
}

std::vector< ::example::thrift29::Struct0> Struct2::get_field6() && {
  return std::move(field6);
}

const std::set<int16_t>& Struct2::get_field7() const& {
  return field7;
}

std::set<int16_t> Struct2::get_field7() && {
  return std::move(field7);
}

const std::set<int32_t>& Struct2::get_field11() const& {
  return field11;
}

std::set<int32_t> Struct2::get_field11() && {
  return std::move(field11);
}

const std::vector<double>& Struct2::get_field12() const& {
  return field12;
}

std::vector<double> Struct2::get_field12() && {
  return std::move(field12);
}

void Struct2::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_LIST;
  }
}

void swap(Struct2& a, Struct2& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct2::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct2::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct2::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct2::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct2::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct2::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct2::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct2::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct3::__clear() {
  // clear all fields
  field1.clear();
  field2 = 0;
  field3 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  __isset.__clear();
}

bool Struct3::operator==(const Struct3& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  return true;
}

const std::set<std::map<int8_t, int32_t>>& Struct3::get_field1() const& {
  return field1;
}

std::set<std::map<int8_t, int32_t>> Struct3::get_field1() && {
  return std::move(field1);
}

void Struct3::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_STRING;
  }
}

void swap(Struct3& a, Struct3& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct3::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct3::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct3::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct3::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct3::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct3::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct3::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct3::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct4::__clear() {
  // clear all fields
  field1.clear();
  field2.clear();
  field3.clear();
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  __isset.__clear();
}

bool Struct4::operator==(const Struct4& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field4, rhs.field4))) {
    return false;
  }
  return true;
}

const std::set<int8_t>& Struct4::get_field1() const& {
  return field1;
}

std::set<int8_t> Struct4::get_field1() && {
  return std::move(field1);
}

const std::map<bool, std::string>& Struct4::get_field2() const& {
  return field2;
}

std::map<bool, std::string> Struct4::get_field2() && {
  return std::move(field2);
}

const std::vector<std::map<std::set<int32_t>, bool>>& Struct4::get_field3() const& {
  return field3;
}

std::vector<std::map<std::set<int32_t>, bool>> Struct4::get_field3() && {
  return std::move(field3);
}

void Struct4::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
}

void swap(Struct4& a, Struct4& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct4::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct4::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct4::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct4::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct4::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct4::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct4::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct4::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct5::__clear() {
  // clear all fields
  field1.clear();
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3.clear();
  field4.clear();
  field5 = 0;
  field6 = 0;
  field7.clear();
  field8 = 0;
  field9 = 0;
  field10.clear();
  __isset.__clear();
}

bool Struct5::operator==(const Struct5& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  return true;
}

const std::vector<float>& Struct5::get_field1() const& {
  return field1;
}

std::vector<float> Struct5::get_field1() && {
  return std::move(field1);
}

const std::map<bool, std::map<std::string, float>>& Struct5::get_field3() const& {
  return field3;
}

std::map<bool, std::map<std::string, float>> Struct5::get_field3() && {
  return std::move(field3);
}

const std::map<double, int32_t>& Struct5::get_field4() const& {
  return field4;
}

std::map<double, int32_t> Struct5::get_field4() && {
  return std::move(field4);
}

const std::vector<float>& Struct5::get_field7() const& {
  return field7;
}

std::vector<float> Struct5::get_field7() && {
  return std::move(field7);
}

const std::set<int8_t>& Struct5::get_field10() const& {
  return field10;
}

std::set<int8_t> Struct5::get_field10() && {
  return std::move(field10);
}

void Struct5::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_SET;
  }
}

void swap(Struct5& a, Struct5& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct5::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct5::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct5::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct5::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct5::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct5::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct5::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct5::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct6::__clear() {
  // clear all fields
  field1 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3.clear();
  field4.clear();
  field5.clear();
  field6.clear();
  field7.clear();
  field8.clear();
  field9 = 0;
  field10.clear();
  field11 = 0;
  field12 = 0;
  field13.clear();
  field14.clear();
  field15 = 0;
  field16.clear();
  field17 = 0;
  field18 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field19.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field20);
  __isset.__clear();
}

bool Struct6::operator==(const Struct6& rhs) const {
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field1, rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field18, rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  if (!((field20 == rhs.field20))) {
    return false;
  }
  return true;
}

const std::set<double>& Struct6::get_field3() const& {
  return field3;
}

std::set<double> Struct6::get_field3() && {
  return std::move(field3);
}

const std::vector<std::string>& Struct6::get_field4() const& {
  return field4;
}

std::vector<std::string> Struct6::get_field4() && {
  return std::move(field4);
}

const std::vector<int8_t>& Struct6::get_field5() const& {
  return field5;
}

std::vector<int8_t> Struct6::get_field5() && {
  return std::move(field5);
}

const std::vector<int64_t>& Struct6::get_field6() const& {
  return field6;
}

std::vector<int64_t> Struct6::get_field6() && {
  return std::move(field6);
}

const std::map<bool, std::vector<int64_t>>& Struct6::get_field7() const& {
  return field7;
}

std::map<bool, std::vector<int64_t>> Struct6::get_field7() && {
  return std::move(field7);
}

const std::set<std::vector<float>>& Struct6::get_field8() const& {
  return field8;
}

std::set<std::vector<float>> Struct6::get_field8() && {
  return std::move(field8);
}

const std::set<double>& Struct6::get_field10() const& {
  return field10;
}

std::set<double> Struct6::get_field10() && {
  return std::move(field10);
}

const std::map<int8_t, int8_t>& Struct6::get_field13() const& {
  return field13;
}

std::map<int8_t, int8_t> Struct6::get_field13() && {
  return std::move(field13);
}

const std::set<std::string>& Struct6::get_field14() const& {
  return field14;
}

std::set<std::string> Struct6::get_field14() && {
  return std::move(field14);
}

const std::set<std::map<int64_t, std::set<float>>>& Struct6::get_field16() const& {
  return field16;
}

std::set<std::map<int64_t, std::set<float>>> Struct6::get_field16() && {
  return std::move(field16);
}

const std::map<int32_t, float>& Struct6::get_field19() const& {
  return field19;
}

std::map<int32_t, float> Struct6::get_field19() && {
  return std::move(field19);
}

const  ::example::thrift29::Struct0& Struct6::get_field20() const& {
  return field20;
}

 ::example::thrift29::Struct0 Struct6::get_field20() && {
  return std::move(field20);
}

void Struct6::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field20") {
    fid = 20;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct6& a, Struct6& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.field20, b.field20);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct6::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct6::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct6::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct6::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct6::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct6::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct6::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct6::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct7::__clear() {
  // clear all fields
  field1 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field2 = 0;
  field3.clear();
  field4.clear();
  field5.clear();
  field6.clear();
  field7 = 0;
  field8 = 0;
  field9.clear();
  field10 = 0;
  field11.clear();
  field12 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct1>::clear(&field13);
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct1>::clear(&field14);
  field15 = 0;
  field16.clear();
  field17.clear();
  __isset.__clear();
}

bool Struct7::operator==(const Struct7& rhs) const {
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field1, rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  return true;
}

const std::vector<float>& Struct7::get_field3() const& {
  return field3;
}

std::vector<float> Struct7::get_field3() && {
  return std::move(field3);
}

const std::set<int16_t>& Struct7::get_field4() const& {
  return field4;
}

std::set<int16_t> Struct7::get_field4() && {
  return std::move(field4);
}

const std::set<int64_t>& Struct7::get_field5() const& {
  return field5;
}

std::set<int64_t> Struct7::get_field5() && {
  return std::move(field5);
}

const std::vector<std::string>& Struct7::get_field6() const& {
  return field6;
}

std::vector<std::string> Struct7::get_field6() && {
  return std::move(field6);
}

const std::set<int16_t>& Struct7::get_field9() const& {
  return field9;
}

std::set<int16_t> Struct7::get_field9() && {
  return std::move(field9);
}

const std::set<std::string>& Struct7::get_field11() const& {
  return field11;
}

std::set<std::string> Struct7::get_field11() && {
  return std::move(field11);
}

const  ::example::thrift29::Struct1& Struct7::get_field13() const& {
  return field13;
}

 ::example::thrift29::Struct1 Struct7::get_field13() && {
  return std::move(field13);
}

const  ::example::thrift29::Struct1& Struct7::get_field14() const& {
  return field14;
}

 ::example::thrift29::Struct1 Struct7::get_field14() && {
  return std::move(field14);
}

const std::vector<double>& Struct7::get_field16() const& {
  return field16;
}

std::vector<double> Struct7::get_field16() && {
  return std::move(field16);
}

const std::map<std::string, int8_t>& Struct7::get_field17() const& {
  return field17;
}

std::map<std::string, int8_t> Struct7::get_field17() && {
  return std::move(field17);
}

void Struct7::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct7& a, Struct7& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct7::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct7::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct7::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct7::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct7::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct7::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct7::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct7::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct8::__clear() {
  // clear all fields
  field1 = 0;
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3.clear();
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field5 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field6 = 0;
  field7 = 0;
  field8 = 0;
  field9 = 0;
  field10 = 0;
  field11 = 0;
  field12 = 0;
  field13 = 0;
  field14.clear();
  field15 = 0;
  field16.clear();
  field17.clear();
  field18 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field19 = 0;
  field20.clear();
  field21 = 0;
  field22 = 0;
  field23 = 0;
  field24.clear();
  field25 = 0;
  field26.clear();
  field27 = 0;
  field28.clear();
  field29.clear();
  field30 = 0;
  field31.clear();
  field32 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field33.clear();
  field34 = 0;
  field35.clear();
  field36 = 0;
  field37 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct6>::clear(&field38);
  field39 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field40 = 0;
  field41 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field42.clear();
  field43.clear();
  field44.clear();
  field45 = 0;
  field46.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct1>::clear(&field47);
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct1>::clear(&field48);
  __isset.__clear();
}

bool Struct8::operator==(const Struct8& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  if (!((field20 == rhs.field20))) {
    return false;
  }
  if (!((field21 == rhs.field21))) {
    return false;
  }
  if (!((field22 == rhs.field22))) {
    return false;
  }
  if (!((field23 == rhs.field23))) {
    return false;
  }
  if (!((field24 == rhs.field24))) {
    return false;
  }
  if (!((field25 == rhs.field25))) {
    return false;
  }
  if (!((field26 == rhs.field26))) {
    return false;
  }
  if (!((field27 == rhs.field27))) {
    return false;
  }
  if (!((field28 == rhs.field28))) {
    return false;
  }
  if (!((field29 == rhs.field29))) {
    return false;
  }
  if (!((field30 == rhs.field30))) {
    return false;
  }
  if (!((field31 == rhs.field31))) {
    return false;
  }
  if (!((field32 == rhs.field32))) {
    return false;
  }
  if (!((field33 == rhs.field33))) {
    return false;
  }
  if (!((field34 == rhs.field34))) {
    return false;
  }
  if (!((field35 == rhs.field35))) {
    return false;
  }
  if (!((field36 == rhs.field36))) {
    return false;
  }
  if (!((field37 == rhs.field37))) {
    return false;
  }
  if (!((field38 == rhs.field38))) {
    return false;
  }
  if (!((field39 == rhs.field39))) {
    return false;
  }
  if (!((field40 == rhs.field40))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field41, rhs.field41))) {
    return false;
  }
  if (!((field42 == rhs.field42))) {
    return false;
  }
  if (!((field43 == rhs.field43))) {
    return false;
  }
  if (!((field44 == rhs.field44))) {
    return false;
  }
  if (!((field45 == rhs.field45))) {
    return false;
  }
  if (!((field46 == rhs.field46))) {
    return false;
  }
  if (!((field47 == rhs.field47))) {
    return false;
  }
  if (!((field48 == rhs.field48))) {
    return false;
  }
  return true;
}

const std::vector<bool>& Struct8::get_field3() const& {
  return field3;
}

std::vector<bool> Struct8::get_field3() && {
  return std::move(field3);
}

const std::map< ::example::thrift29::Struct5, float>& Struct8::get_field14() const& {
  return field14;
}

std::map< ::example::thrift29::Struct5, float> Struct8::get_field14() && {
  return std::move(field14);
}

const std::vector<int32_t>& Struct8::get_field16() const& {
  return field16;
}

std::vector<int32_t> Struct8::get_field16() && {
  return std::move(field16);
}

const std::set<std::vector< ::example::thrift29::Struct0>>& Struct8::get_field17() const& {
  return field17;
}

std::set<std::vector< ::example::thrift29::Struct0>> Struct8::get_field17() && {
  return std::move(field17);
}

const std::set<int64_t>& Struct8::get_field20() const& {
  return field20;
}

std::set<int64_t> Struct8::get_field20() && {
  return std::move(field20);
}

const std::vector<double>& Struct8::get_field24() const& {
  return field24;
}

std::vector<double> Struct8::get_field24() && {
  return std::move(field24);
}

const std::map< ::example::thrift29::Struct0, double>& Struct8::get_field26() const& {
  return field26;
}

std::map< ::example::thrift29::Struct0, double> Struct8::get_field26() && {
  return std::move(field26);
}

const std::set<double>& Struct8::get_field28() const& {
  return field28;
}

std::set<double> Struct8::get_field28() && {
  return std::move(field28);
}

const std::set<std::string>& Struct8::get_field29() const& {
  return field29;
}

std::set<std::string> Struct8::get_field29() && {
  return std::move(field29);
}

const std::set<std::vector<int16_t>>& Struct8::get_field31() const& {
  return field31;
}

std::set<std::vector<int16_t>> Struct8::get_field31() && {
  return std::move(field31);
}

const std::vector< ::example::thrift29::Struct3>& Struct8::get_field33() const& {
  return field33;
}

std::vector< ::example::thrift29::Struct3> Struct8::get_field33() && {
  return std::move(field33);
}

const std::vector<double>& Struct8::get_field35() const& {
  return field35;
}

std::vector<double> Struct8::get_field35() && {
  return std::move(field35);
}

const  ::example::thrift29::Struct6& Struct8::get_field38() const& {
  return field38;
}

 ::example::thrift29::Struct6 Struct8::get_field38() && {
  return std::move(field38);
}

const std::set<float>& Struct8::get_field42() const& {
  return field42;
}

std::set<float> Struct8::get_field42() && {
  return std::move(field42);
}

const std::set<int64_t>& Struct8::get_field43() const& {
  return field43;
}

std::set<int64_t> Struct8::get_field43() && {
  return std::move(field43);
}

const std::vector<float>& Struct8::get_field44() const& {
  return field44;
}

std::vector<float> Struct8::get_field44() && {
  return std::move(field44);
}

const std::set<std::string>& Struct8::get_field46() const& {
  return field46;
}

std::set<std::string> Struct8::get_field46() && {
  return std::move(field46);
}

const  ::example::thrift29::Struct1& Struct8::get_field47() const& {
  return field47;
}

 ::example::thrift29::Struct1 Struct8::get_field47() && {
  return std::move(field47);
}

const  ::example::thrift29::Struct1& Struct8::get_field48() const& {
  return field48;
}

 ::example::thrift29::Struct1 Struct8::get_field48() && {
  return std::move(field48);
}

void Struct8::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field20") {
    fid = 20;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field21") {
    fid = 21;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field22") {
    fid = 22;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field23") {
    fid = 23;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field24") {
    fid = 24;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field25") {
    fid = 25;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field26") {
    fid = 26;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field27") {
    fid = 27;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field28") {
    fid = 28;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field29") {
    fid = 29;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field30") {
    fid = 30;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field31") {
    fid = 31;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field32") {
    fid = 32;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field33") {
    fid = 33;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field34") {
    fid = 34;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field35") {
    fid = 35;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field36") {
    fid = 36;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field37") {
    fid = 37;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field38") {
    fid = 38;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field39") {
    fid = 39;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field40") {
    fid = 40;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field41") {
    fid = 41;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field42") {
    fid = 42;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field43") {
    fid = 43;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field44") {
    fid = 44;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field45") {
    fid = 45;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field46") {
    fid = 46;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field47") {
    fid = 47;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field48") {
    fid = 48;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct8& a, Struct8& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.field20, b.field20);
  swap(a.field21, b.field21);
  swap(a.field22, b.field22);
  swap(a.field23, b.field23);
  swap(a.field24, b.field24);
  swap(a.field25, b.field25);
  swap(a.field26, b.field26);
  swap(a.field27, b.field27);
  swap(a.field28, b.field28);
  swap(a.field29, b.field29);
  swap(a.field30, b.field30);
  swap(a.field31, b.field31);
  swap(a.field32, b.field32);
  swap(a.field33, b.field33);
  swap(a.field34, b.field34);
  swap(a.field35, b.field35);
  swap(a.field36, b.field36);
  swap(a.field37, b.field37);
  swap(a.field38, b.field38);
  swap(a.field39, b.field39);
  swap(a.field40, b.field40);
  swap(a.field41, b.field41);
  swap(a.field42, b.field42);
  swap(a.field43, b.field43);
  swap(a.field44, b.field44);
  swap(a.field45, b.field45);
  swap(a.field46, b.field46);
  swap(a.field47, b.field47);
  swap(a.field48, b.field48);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct8::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct8::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct8::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct8::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct8::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct8::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct8::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct8::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct9::__clear() {
  // clear all fields
  field1 = 0;
  field2 = 0;
  field3.clear();
  field4 = 0;
  __isset.__clear();
}

bool Struct9::operator==(const Struct9& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  return true;
}

const std::set<std::vector<std::string>>& Struct9::get_field3() const& {
  return field3;
}

std::set<std::vector<std::string>> Struct9::get_field3() && {
  return std::move(field3);
}

void Struct9::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I32;
  }
}

void swap(Struct9& a, Struct9& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct9::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct9::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct9::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct9::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct9::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct9::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct9::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct9::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct10::__clear() {
  // clear all fields
  field1.clear();
  field2 = 0;
  field3 = 0;
  field4 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field5);
  __isset.__clear();
}

bool Struct10::operator==(const Struct10& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field4, rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  return true;
}

const std::vector<int16_t>& Struct10::get_field1() const& {
  return field1;
}

std::vector<int16_t> Struct10::get_field1() && {
  return std::move(field1);
}

const  ::example::thrift29::Struct0& Struct10::get_field5() const& {
  return field5;
}

 ::example::thrift29::Struct0 Struct10::get_field5() && {
  return std::move(field5);
}

void Struct10::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct10& a, Struct10& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct10::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct10::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct10::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct10::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct10::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct10::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct10::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct10::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct11::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct2>::clear(&field1);
  field2.clear();
  field3 = 0;
  field4.clear();
  field5 = 0;
  field6 = 0;
  field7.clear();
  field8 = 0;
  field9 = 0;
  field10.clear();
  field11.clear();
  field12 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field13.clear();
  field14 = 0;
  field15.clear();
  field16 = 0;
  field17 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field18.clear();
  field19 = 0;
  __isset.__clear();
}

bool Struct11::operator==(const Struct11& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field12, rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field17, rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  if (!((field19 == rhs.field19))) {
    return false;
  }
  return true;
}

const  ::example::thrift29::Struct2& Struct11::get_field1() const& {
  return field1;
}

 ::example::thrift29::Struct2 Struct11::get_field1() && {
  return std::move(field1);
}

const std::vector<std::vector<int64_t>>& Struct11::get_field2() const& {
  return field2;
}

std::vector<std::vector<int64_t>> Struct11::get_field2() && {
  return std::move(field2);
}

const std::vector<std::string>& Struct11::get_field4() const& {
  return field4;
}

std::vector<std::string> Struct11::get_field4() && {
  return std::move(field4);
}

const std::vector<double>& Struct11::get_field7() const& {
  return field7;
}

std::vector<double> Struct11::get_field7() && {
  return std::move(field7);
}

const std::vector<std::set<bool>>& Struct11::get_field10() const& {
  return field10;
}

std::vector<std::set<bool>> Struct11::get_field10() && {
  return std::move(field10);
}

const std::vector<int64_t>& Struct11::get_field11() const& {
  return field11;
}

std::vector<int64_t> Struct11::get_field11() && {
  return std::move(field11);
}

const std::vector<std::vector<std::string>>& Struct11::get_field13() const& {
  return field13;
}

std::vector<std::vector<std::string>> Struct11::get_field13() && {
  return std::move(field13);
}

const std::vector<std::string>& Struct11::get_field15() const& {
  return field15;
}

std::vector<std::string> Struct11::get_field15() && {
  return std::move(field15);
}

const std::map<std::string, bool>& Struct11::get_field18() const& {
  return field18;
}

std::map<std::string, bool> Struct11::get_field18() && {
  return std::move(field18);
}

void Struct11::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field19") {
    fid = 19;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
}

void swap(Struct11& a, Struct11& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.field19, b.field19);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct11::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct11::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct11::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct11::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct11::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct11::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct11::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct11::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct12::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct3>::clear(&field1);
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3 = 0;
  field4 = 0;
  field5.clear();
  __isset.__clear();
}

bool Struct12::operator==(const Struct12& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  return true;
}

const  ::example::thrift29::Struct3& Struct12::get_field1() const& {
  return field1;
}

 ::example::thrift29::Struct3 Struct12::get_field1() && {
  return std::move(field1);
}

const std::map< ::example::thrift29::Struct3, double>& Struct12::get_field5() const& {
  return field5;
}

std::map< ::example::thrift29::Struct3, double> Struct12::get_field5() && {
  return std::move(field5);
}

void Struct12::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct12& a, Struct12& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct12::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct12::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct12::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct12::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct12::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct12::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct12::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct12::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct13::__clear() {
  // clear all fields
  field1.clear();
  field2.clear();
  field3.clear();
  field4 = 0;
  field5.clear();
  field6.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct7>::clear(&field7);
  field8 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field9);
  __isset.__clear();
}

bool Struct13::operator==(const Struct13& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  return true;
}

const std::map<int64_t, int32_t>& Struct13::get_field1() const& {
  return field1;
}

std::map<int64_t, int32_t> Struct13::get_field1() && {
  return std::move(field1);
}

const std::vector<int8_t>& Struct13::get_field2() const& {
  return field2;
}

std::vector<int8_t> Struct13::get_field2() && {
  return std::move(field2);
}

const std::vector<bool>& Struct13::get_field3() const& {
  return field3;
}

std::vector<bool> Struct13::get_field3() && {
  return std::move(field3);
}

const std::vector<bool>& Struct13::get_field5() const& {
  return field5;
}

std::vector<bool> Struct13::get_field5() && {
  return std::move(field5);
}

const std::set<bool>& Struct13::get_field6() const& {
  return field6;
}

std::set<bool> Struct13::get_field6() && {
  return std::move(field6);
}

const  ::example::thrift29::Struct7& Struct13::get_field7() const& {
  return field7;
}

 ::example::thrift29::Struct7 Struct13::get_field7() && {
  return std::move(field7);
}

const  ::example::thrift29::Struct0& Struct13::get_field9() const& {
  return field9;
}

 ::example::thrift29::Struct0 Struct13::get_field9() && {
  return std::move(field9);
}

void Struct13::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct13& a, Struct13& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct13::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct13::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct13::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct13::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct13::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct13::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct13::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct13::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct14::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct6>::clear(&field1);
  field2 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field3.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct6>::clear(&field4);
  field5.clear();
  field6.clear();
  field7 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct9>::clear(&field8);
  field9 = 0;
  field10.clear();
  field11.clear();
  field12.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct2>::clear(&field13);
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct6>::clear(&field14);
  field15.clear();
  field16.clear();
  field17.clear();
  field18 = 0;
  __isset.__clear();
}

bool Struct14::operator==(const Struct14& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field2, rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!((field9 == rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  if (!((field12 == rhs.field12))) {
    return false;
  }
  if (!((field13 == rhs.field13))) {
    return false;
  }
  if (!((field14 == rhs.field14))) {
    return false;
  }
  if (!((field15 == rhs.field15))) {
    return false;
  }
  if (!((field16 == rhs.field16))) {
    return false;
  }
  if (!((field17 == rhs.field17))) {
    return false;
  }
  if (!((field18 == rhs.field18))) {
    return false;
  }
  return true;
}

const  ::example::thrift29::Struct6& Struct14::get_field1() const& {
  return field1;
}

 ::example::thrift29::Struct6 Struct14::get_field1() && {
  return std::move(field1);
}

const std::vector<std::set<int8_t>>& Struct14::get_field3() const& {
  return field3;
}

std::vector<std::set<int8_t>> Struct14::get_field3() && {
  return std::move(field3);
}

const  ::example::thrift29::Struct6& Struct14::get_field4() const& {
  return field4;
}

 ::example::thrift29::Struct6 Struct14::get_field4() && {
  return std::move(field4);
}

const std::vector<std::map<double, int8_t>>& Struct14::get_field5() const& {
  return field5;
}

std::vector<std::map<double, int8_t>> Struct14::get_field5() && {
  return std::move(field5);
}

const std::vector<double>& Struct14::get_field6() const& {
  return field6;
}

std::vector<double> Struct14::get_field6() && {
  return std::move(field6);
}

const  ::example::thrift29::Struct9& Struct14::get_field8() const& {
  return field8;
}

 ::example::thrift29::Struct9 Struct14::get_field8() && {
  return std::move(field8);
}

const std::vector<int64_t>& Struct14::get_field10() const& {
  return field10;
}

std::vector<int64_t> Struct14::get_field10() && {
  return std::move(field10);
}

const std::vector<int64_t>& Struct14::get_field11() const& {
  return field11;
}

std::vector<int64_t> Struct14::get_field11() && {
  return std::move(field11);
}

const std::set<std::string>& Struct14::get_field12() const& {
  return field12;
}

std::set<std::string> Struct14::get_field12() && {
  return std::move(field12);
}

const  ::example::thrift29::Struct2& Struct14::get_field13() const& {
  return field13;
}

 ::example::thrift29::Struct2 Struct14::get_field13() && {
  return std::move(field13);
}

const  ::example::thrift29::Struct6& Struct14::get_field14() const& {
  return field14;
}

 ::example::thrift29::Struct6 Struct14::get_field14() && {
  return std::move(field14);
}

const std::vector< ::example::thrift29::Struct9>& Struct14::get_field15() const& {
  return field15;
}

std::vector< ::example::thrift29::Struct9> Struct14::get_field15() && {
  return std::move(field15);
}

const std::set<std::map<std::string, bool>>& Struct14::get_field16() const& {
  return field16;
}

std::set<std::map<std::string, bool>> Struct14::get_field16() && {
  return std::move(field16);
}

const std::set<double>& Struct14::get_field17() const& {
  return field17;
}

std::set<double> Struct14::get_field17() && {
  return std::move(field17);
}

void Struct14::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field12") {
    fid = 12;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field13") {
    fid = 13;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field14") {
    fid = 14;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field15") {
    fid = 15;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field16") {
    fid = 16;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field17") {
    fid = 17;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field18") {
    fid = 18;
    _ftype = apache::thrift::protocol::T_FLOAT;
  }
}

void swap(Struct14& a, Struct14& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.field12, b.field12);
  swap(a.field13, b.field13);
  swap(a.field14, b.field14);
  swap(a.field15, b.field15);
  swap(a.field16, b.field16);
  swap(a.field17, b.field17);
  swap(a.field18, b.field18);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct14::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct14::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct14::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct14::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct14::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct14::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct14::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct14::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct15::__clear() {
  // clear all fields
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct6>::clear(&field1);
  field2.clear();
  field3 = 0;
  field4.clear();
  field5 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field6.clear();
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct4>::clear(&field7);
  field8.clear();
  field9 = apache::thrift::StringTraits< std::string>::fromStringLiteral("");
  field10 = 0;
  field11.clear();
  __isset.__clear();
}

bool Struct15::operator==(const Struct15& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  if (!(apache::thrift::StringTraits<std::string>::isEqual(field9, rhs.field9))) {
    return false;
  }
  if (!((field10 == rhs.field10))) {
    return false;
  }
  if (!((field11 == rhs.field11))) {
    return false;
  }
  return true;
}

const  ::example::thrift29::Struct6& Struct15::get_field1() const& {
  return field1;
}

 ::example::thrift29::Struct6 Struct15::get_field1() && {
  return std::move(field1);
}

const std::vector<std::string>& Struct15::get_field2() const& {
  return field2;
}

std::vector<std::string> Struct15::get_field2() && {
  return std::move(field2);
}

const std::set<float>& Struct15::get_field4() const& {
  return field4;
}

std::set<float> Struct15::get_field4() && {
  return std::move(field4);
}

const std::map<std::set<float>, int32_t>& Struct15::get_field6() const& {
  return field6;
}

std::map<std::set<float>, int32_t> Struct15::get_field6() && {
  return std::move(field6);
}

const  ::example::thrift29::Struct4& Struct15::get_field7() const& {
  return field7;
}

 ::example::thrift29::Struct4 Struct15::get_field7() && {
  return std::move(field7);
}

const std::map<std::string, std::map<std::map<std::string, int16_t>, int8_t>>& Struct15::get_field8() const& {
  return field8;
}

std::map<std::string, std::map<std::map<std::string, int16_t>, int8_t>> Struct15::get_field8() && {
  return std::move(field8);
}

const std::map<int32_t, float>& Struct15::get_field11() const& {
  return field11;
}

std::map<int32_t, float> Struct15::get_field11() && {
  return std::move(field11);
}

void Struct15::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field9") {
    fid = 9;
    _ftype = apache::thrift::protocol::T_STRING;
  }
  else if (_fname == "field10") {
    fid = 10;
    _ftype = apache::thrift::protocol::T_BOOL;
  }
  else if (_fname == "field11") {
    fid = 11;
    _ftype = apache::thrift::protocol::T_MAP;
  }
}

void swap(Struct15& a, Struct15& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.field9, b.field9);
  swap(a.field10, b.field10);
  swap(a.field11, b.field11);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct15::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct15::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct15::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct15::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct15::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct15::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct15::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct15::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct16::__clear() {
  // clear all fields
  field1.clear();
  field2.clear();
  field3.clear();
  field4 = 0;
  field5.clear();
  field6 = 0;
  field7 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct0>::clear(&field8);
  __isset.__clear();
}

bool Struct16::operator==(const Struct16& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  if (!((field8 == rhs.field8))) {
    return false;
  }
  return true;
}

const std::vector<int32_t>& Struct16::get_field1() const& {
  return field1;
}

std::vector<int32_t> Struct16::get_field1() && {
  return std::move(field1);
}

const std::map<double, std::string>& Struct16::get_field2() const& {
  return field2;
}

std::map<double, std::string> Struct16::get_field2() && {
  return std::move(field2);
}

const std::vector<std::string>& Struct16::get_field3() const& {
  return field3;
}

std::vector<std::string> Struct16::get_field3() && {
  return std::move(field3);
}

const std::set<std::map<float, std::set<float>>>& Struct16::get_field5() const& {
  return field5;
}

std::set<std::map<float, std::set<float>>> Struct16::get_field5() && {
  return std::move(field5);
}

const  ::example::thrift29::Struct0& Struct16::get_field8() const& {
  return field8;
}

 ::example::thrift29::Struct0 Struct16::get_field8() && {
  return std::move(field8);
}

void Struct16::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_LIST;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_I64;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field8") {
    fid = 8;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct16& a, Struct16& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.field8, b.field8);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct16::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct16::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct16::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct16::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct16::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct16::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct16::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct16::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
namespace example { namespace thrift29 {

void Struct17::__clear() {
  // clear all fields
  field1.clear();
  field2 = 0;
  field3 = 0;
  field4 = 0;
  field5.clear();
  field6 = 0;
  ::apache::thrift::Cpp2Ops<  ::example::thrift29::Struct1>::clear(&field7);
  __isset.__clear();
}

bool Struct17::operator==(const Struct17& rhs) const {
  if (!((field1 == rhs.field1))) {
    return false;
  }
  if (!((field2 == rhs.field2))) {
    return false;
  }
  if (!((field3 == rhs.field3))) {
    return false;
  }
  if (!((field4 == rhs.field4))) {
    return false;
  }
  if (!((field5 == rhs.field5))) {
    return false;
  }
  if (!((field6 == rhs.field6))) {
    return false;
  }
  if (!((field7 == rhs.field7))) {
    return false;
  }
  return true;
}

const std::set<std::string>& Struct17::get_field1() const& {
  return field1;
}

std::set<std::string> Struct17::get_field1() && {
  return std::move(field1);
}

const std::map<int16_t, bool>& Struct17::get_field5() const& {
  return field5;
}

std::map<int16_t, bool> Struct17::get_field5() && {
  return std::move(field5);
}

const  ::example::thrift29::Struct1& Struct17::get_field7() const& {
  return field7;
}

 ::example::thrift29::Struct1 Struct17::get_field7() && {
  return std::move(field7);
}

void Struct17::translateFieldName(FOLLY_MAYBE_UNUSED folly::StringPiece _fname, FOLLY_MAYBE_UNUSED int16_t& fid, FOLLY_MAYBE_UNUSED apache::thrift::protocol::TType& _ftype) {
  if (false) {}
  else if (_fname == "field1") {
    fid = 1;
    _ftype = apache::thrift::protocol::T_SET;
  }
  else if (_fname == "field2") {
    fid = 2;
    _ftype = apache::thrift::protocol::T_BYTE;
  }
  else if (_fname == "field3") {
    fid = 3;
    _ftype = apache::thrift::protocol::T_DOUBLE;
  }
  else if (_fname == "field4") {
    fid = 4;
    _ftype = apache::thrift::protocol::T_I16;
  }
  else if (_fname == "field5") {
    fid = 5;
    _ftype = apache::thrift::protocol::T_MAP;
  }
  else if (_fname == "field6") {
    fid = 6;
    _ftype = apache::thrift::protocol::T_I32;
  }
  else if (_fname == "field7") {
    fid = 7;
    _ftype = apache::thrift::protocol::T_STRUCT;
  }
}

void swap(Struct17& a, Struct17& b) {
  using ::std::swap;
  swap(a.field1, b.field1);
  swap(a.field2, b.field2);
  swap(a.field3, b.field3);
  swap(a.field4, b.field4);
  swap(a.field5, b.field5);
  swap(a.field6, b.field6);
  swap(a.field7, b.field7);
  swap(a.__isset, b.__isset);
}

template uint32_t Struct17::read<>(apache::thrift::BinaryProtocolReader*);
template uint32_t Struct17::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t Struct17::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct17::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t Struct17::read<>(apache::thrift::CompactProtocolReader*);
template uint32_t Struct17::write<>(apache::thrift::CompactProtocolWriter*) const;
template uint32_t Struct17::serializedSize<>(apache::thrift::CompactProtocolWriter const*) const;
template uint32_t Struct17::serializedSizeZC<>(apache::thrift::CompactProtocolWriter const*) const;

}} // example::thrift29
