/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file20_constants.h"

#include <folly/Indestructible.h>

namespace example { namespace thrift20 {

}} // example::thrift20
