/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "file1_constants.h"

#include <folly/Indestructible.h>

namespace example { namespace thrift1 {

}} // example::thrift1
