/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "if/gen-cpp2/file1_constants.h"

#include <folly/Indestructible.h>

namespace cpp2 {

} // cpp2
