/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/protocol/Protocol.h>

#include "file29_types.h"

namespace cpp2 {

struct file29_constants {

};

} // cpp2
