/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "file32_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace example { namespace thrift32 {

struct file32_constants {

};

}} // example::thrift32
